### ISSUE TITLE
[Teste] Lista 4 - Exercício 3, 4 e 5 - Clayton

### ISSUE THREAD

**Issue by claytoncribeiro** [professorlineu/PROA3-2019-2#39]
Fiz os exercícios 3, 4 e 5 da lista 4 .
Quem puder, faz o teste pra verificar se eles estão funcionando.
Obrigado.

https://github.com/professorlineu/PROA3-2019-2/tree/master/Atividades/Clayton_Ribeiro/Lista4

**Comment by martinsleticia** [comment]
Testado,eles funcionaram!

**Comment by isaaccarvalhoalmeida** [comment]
testei e ficou da hora

**Comment by isaaccarvalhoalmeida** [comment]
testei e ficou show de bola o exercicio 4

**Comment by isaaccarvalhoalmeida** [comment]
fiz o teste do exercicio 5 e rodou lindo

**Comment by claytoncribeiro** [comment]
Boa, como todos foram testados eu vou encerrar esse chamado. Obrigado.
